- id: "helm-unittest"
  name: "helm unittest"
  description: "Runs Helm unit tests."
  language: "script"
  entry: "/usr/bin/env helm"
  args: ["unittest", "."]
  types: ["file", "yaml"]
  pass_filenames: false
