name: "unittest"
version: "1.0.3"
usage: "unittest for helm charts"
description: "Unit test for helm chart in YAML with ease to keep your chart functional and robust."
ignoreFlags: false
platformCommand:
  - command: "$HELM_PLUGIN_DIR/untt"
  - os: windows
    command: "$HELM_PLUGIN_DIR\\untt.exe"
platformHooks:
  install:
    - command: "$HELM_PLUGIN_DIR/install-binary.sh"
    - os: windows
      command: "powershell.exe"
      args: 
        - -ExecutionPolicy 
        - Bypass 
        - -File 
        - "$HELM_PLUGIN_DIR\\install-binary.ps1"
  update:
    - command: "$HELM_PLUGIN_DIR/install-binary.sh"
    - os: windows
      command: "powershell.exe" 
      args: 
        - -ExecutionPolicy 
        - Bypass 
        - -File 
        - "$HELM_PLUGIN_DIR\\install-binary.ps1"
