name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  # Common versions
  GO_VERSION: '1.22.x'
  GOLANGCI_VERSION: 'latest'

permissions:
  contents: read

jobs:

  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        # https://github.com/actions/checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: setup go
        # https://github.com/actions/setup-go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: lint
        # https://github.com/golangci/golangci-lint-action
        uses: golangci/golangci-lint-action@v6
        with:
          version: ${{ env.GOLANGCI_VERSION }}
          # remove when linter errors fixed
          args: --issues-exit-code=0
