name: "Correct Helm-Unittest Release"

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  refresh-docker-release:
    name: run docker refresh via reusable release workflow
    uses: ./.github/workflows/release.yml
    with:
      run_release_job: false
      run_docker_publish: true
      helm_tags_per_page: 20
      plugin_tags_per_page: 2
    permissions:
      contents: write # to publish assets to the release
    secrets: 
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
